# -*- coding: utf-8 -*-
"""nltk_download

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dWWoZraqKYiVNyvHNgfsfTvQsTX5L4k
"""

import nltk

def download_nltk_resources():
    resources = ['punkt', 'stopwords']
    for resource in resources:
        try:
            nltk.data.find(f"tokenizers/{resource}")
        except LookupError:
            nltk.download(resource)

download_nltk_resources()