writers_dict = {
    'Aesop': 'Эзоп',
    'Agatha_Christie': 'Агата Кристи',
    'Ahmet_Hamdi_Tanpinar': 'Ахмет Хамди Танпынар',
    'Albert_Camus': 'Альбер Камю',
    'Aldous_Huxley': 'Олдос Хаксли',
    'Alexander_Pushkin': 'Александр Сергеевич Пушкин',
    'Alexandre_Dumas': 'Александр Дюма',
    'Alphonse_Daudet': 'Альфонс Доде',
    'Antoine_De_Saint_Exupery': 'Антуан де Сент-Экзюпери',
    'Anton_Chekhov': 'Антон Павлович Чехов',
    'Aristophanes': 'Аристофан',
    'Arthur_Conan_Doyle': 'Артур Конан Дойл',
    'Arthur_Rimbaud': 'Артур Рембо',
    'Beaumarchais': 'Пьер Огюстен Карон де Бомарше',
    'Bertolt_Brecht': 'Бертольт Брехт',
    'Borges': 'Хорхе Луис Борхес',
    'Boris_Pasternak': 'Борис Леонидович Пастернак',
    'Charles_Baudelaire': 'Шарль Бодлер',
    'Charles_Dickens': 'Чарльз Диккенс',
    'Chingiz_Aitmatov': 'Чингиз Айтматов',
    'Dante_Alighieri': 'Данте Алигьери',
    'Edgar_Allan_Poe': 'Эдгар Аллан По',
    'Erich_Maria_Remarque': 'Эрих Мария Ремарк',
    'Ernest_Hemingway': 'Эрнест Хемингуэй',
    'F_Scott_Fitzgerald': 'Фрэнсис Скотт Фицджеральд',
    'Federico_Garcia_Lorca': 'Федерико Гарсиа Лорка',
    'Francois_Rabelais': 'Франсуа Рабле',
    'Franz_Kafka': 'Франц Кафка',
    'Fyodor_Dostoyevsky': 'Фёдор Михайлович Достоевский',
    'Gabriel_Garcia_Marquez': 'Габриэль Гарсиа Маркес',
    'Geoffrey_Chaucer': 'Джеффри Чосер',
    'George_Bernard_Shaw': 'Джордж Бернард Шоу',
    'George_Orwell': 'Джордж Оруэлл',
    'Giovanni_Boccaccio': 'Джованни Боккаччо',
    'Guy_De_Maupassant': 'Ги де Мопассан',
    'H_P_Lovecraft': 'Говард Филлипс Лавкрафт',
    'Hans_Christian_Andersen': 'Ханс Кристиан Андерсен',
    'Haruki_Murakami': 'Харуки Мураками',
    'Herman_Melville': 'Герман Мелвилл',
    'Hermann_Hesse': 'Герман Гессе',
    'Honore_De_Balzac': 'Оноре де Бальзак',
    'Isaac_Asimov': 'Айзек Азимов',
    'Italo_Calvino': 'Итало Кальвино',
    'Ivan_Turgenev': 'Иван Сергеевич Тургенев',
    'J_D_Salinger': 'Джером Дэвид Сэлинджер',
    'J_M_Coetzee': 'Джон Максвелл Кутзее',
    'J_R_R_Tolkien': 'Джон Рональд Руэл Толкин',
    'Jack_London': 'Джек Лондон',
    'Jalaluddin_Muhammad_Rumi': 'Джалаладдин Мухаммад Руми',
    'James_Fenimore_Cooper': 'Джеймс Фенимор Купер',
    'James_Joyce': 'Джеймс Джойс',
    'Jane_Austen': 'Джейн Остин',
    'Jean_De_La_Fontaine': 'Жан де Лафонтен',
    'Jean_Paul_Sartre': 'Жан-Поль Сартр',
    'Jean_Racine': 'Жан Расин',
    'Johann_Wolfgang_Von_Goethe': 'Иоганн Вольфганг фон Гёте',
    'John_Fante': 'Джон Фанте',
    'John_Keats': 'Джон Китс',
    'John_Steinbeck': 'Джон Стейнбек',
    'Jose_Saramago': 'Жозе Сарамаго',
    'Jules_Verne': 'Жюль Верн',
    'Julio_Cortazar': 'Хулио Кортасар',
    'Kazuo_Ishiguro': 'Кадзуо Исигуро',
    'Lev_Tolstoy': 'Лев Николаевич Толстой',
    'Lord_Byron': 'Джордж Гордон Байрон',
    'Louis_Ferdinand_Celine': 'Луи-Фердинанд Селин',
    'Marcel_Proust': 'Марсель Пруст',
    'Mario_Vargas_Llosa': 'Марио Варгас Льоса',
    'Mark_Twain': 'Марк Твен',
    'Maxim_Gorky': 'Максим Горький',
    'Mayne_Reid': 'Томас Майн Рид',
    'Miguel_De_Cervantes_Saavedra': 'Мигель де Сервантес Сааведра',
    'Mikhail_Lermontov': 'Михаил Юрьевич Лермонтов',
    'Mikhail_Sholokhov': 'Михаил Александрович Шолохов',
    'Milan_Kundera': 'Милан Кундера',
    'Moliere': 'Жан-Батист Мольер',
    'Naguib_Mahfouz': 'Нагиб Махфуз',
    'Neil_Gaiman': 'Нил Гейман',
    'Nikolay_Gogol': 'Николай Васильевич Гоголь',
    'Nikos_Kazantzakis': 'Никос Казандзакис',
    'O_Henry': 'О. Генри',
    'Oscar_Wilde': 'Оскар Уайльд',
    'Pablo_Neruda': 'Пабло Неруда',
    'Publius_Vergilius_Maro': 'Публий Вергилий Марон',
    'Rainer_Maria_Rilke': 'Райнер Мария Рильке',
    'Robert_Louis_Stevenson': 'Роберт Льюис Стивенсон',
    'Salman_Rushdie': 'Салман Рушди',
    'Sophocles': 'Софокл',
    'Stefan_Zweig': 'Стефан Цвейг',
    'Stendhal': 'Анри Бейль (Стендаль)',
    'Stephen_King': 'Стивен Кинг',
    'T_S_Eliot': 'Томас Стернз Элиот',
    'Thomas_Mann': 'Томас Манн',
    'Thomas_Pynchon': 'Томас Пинчон',
    'Umberto_Eco': 'Умберто Эко',
    'Ursula_K_Le_Guin': 'Урсула Ле Гуин',
    'Victor_Hugo': 'Виктор Гюго',
    'Virginia_Woolf': 'Вирджиния Вулф',
    'William_Faulkner': 'Уильям Фолкнер',
    'William_Shakespeare': 'Уильям Шекспир'
}
